version: '3'
 
services:
   db:
     build: ./db
     container_name: mysql-${APP_NAME}
     volumes:
       - db:/var/lib/mysql
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
     ports:
       - "3307:3306"
     restart: always
     command: "--default-authentication-plugin=mysql_native_password"
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
       MYSQL_DATABASE: ${DB_NAME}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}
 
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wp-${APP_NAME}
     restart: always
     volumes:
       - ./wp-content:/var/www/html/wp-content
     ports:
       - "8080:80"
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: ${DB_USER}
       WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
       WORDPRESS_DB_NAME: ${DB_NAME}
 
   nginx:
     depends_on:
       - wordpress
     restart: always
     build: ./nginx
     container_name: nginx-${APP_NAME}
     volumes:
        - "./nginx-conf/:/etc/nginx/templates/"
        - ./certs:/etc/certs
    #  environment:
    #     - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
    #     - "DOMAIN=${DOMAIN}"
     ports:
       - "80:80"
       - "443:443"
   phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-${APP_NAME}
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  db:
    driver: local