version: '3'
 
services:
   db:
     build: ./db
     container_name: mysql-training
     volumes:
       - db:/var/lib/mysql
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
     ports:
       - "3307:3306"
     restart: always
     command: "--default-authentication-plugin=mysql_native_password"
     environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_DATABASE: wordpress
       MYSQL_USER: hotuong
       MYSQL_PASSWORD: 123456
 
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wp-training
     restart: always
     volumes:
       - ./wp-content:/var/www/html/wp-content
     ports:
       - "8080:80"
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: hotuong
       WORDPRESS_DB_PASSWORD: 123456
       WORDPRESS_DB_NAME: wordpress
 
   nginx:
     depends_on:
       - wordpress
     restart: always
     build: ./nginx-conf
     container_name: nginx-training
     ports:
       - "80:80"
   phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  db:
    driver: local